### ISSUE TITLE
Dont work on xcode

### ISSUE THREAD

**Issue by vadermemo** [MosesEsan/mesan-react-native-cli-authentication-app#1]
Hi friend MosesEsan,

  I try compile and deploy your source, just cloning from github but when I run on xcode this stacktrace appears:

Showing All Messages
/Users/..../Documents/workspaces/react-native/mesan-react-native-cli-authentication-app/ios/Pods/Target Support Files/Pods-ReactNativeAuthentication/Pods-ReactNativeAuthentication.debug.xcconfig: unable to open file (in target "ReactNativeAuthentication" in project "ReactNativeAuthentication")

Any idea for resolve this issue?

**Comment by yalva** [comment]
> Hi friend MosesEsan,
> 
> I try compile and deploy your source, just cloning from github but when I run on xcode this stacktrace appears:
> 
> Showing All Messages
> /Users/..../Documents/workspaces/react-native/mesan-react-native-cli-authentication-app/ios/Pods/Target Support Files/Pods-ReactNativeAuthentication/Pods-ReactNativeAuthentication.debug.xcconfig: unable to open file (in target "ReactNativeAuthentication" in project "ReactNativeAuthentication")
> 
> Any idea for resolve this issue?

Did you run these command before opening the project from xcode?
yarn install
cd ios && pod install

**Comment by MosesEsan** [comment]
You have to run those commands after cloning
