### ISSUE TITLE
Error while updating property 'editable' of a view managed by AndroidTextInput

### ISSUE THREAD

**Issue by qonteo** [MosesEsan/mesan-react-native-cli-authentication-app#2]
Hi Moses,
I've downloaded the source code available in the repository mesan-react-native-cli-authentication-app, however, I'm not able to start the app. It returned an error related to AndroidInputText. See the error bellow

I ran the following commands, in sequence
$ git clone https://github.com/MosesEsan/mesan-react-native-cli-authentication-app.git
$ cd mesan-react-native-cli-authentication-app
$ npm install  && npm start 

in the other prompt
$ npx react-native run-android

Version of Framework and libraries are
node -v
v12.16.2

npm -v
6.14.5

react-native -v
react-native-cli: 2.0.1
react-native: 0.61.5

Error while updating property 'editable' of a view managed by androidTextInput

![image](https://user-images.githubusercontent.com/64494340/82593907-9fa59b00-9b79-11ea-9675-42443f7a43d8.png)

**Comment by qonteo** [comment]
I found similar issues, but they didn't help much because I haven't found where you used that property. (i.e.  what's the file? or what is the lib?) 
Where do I find the respective property in your code?

Best wishes,
I

**Comment by qonteo** [comment]
I found the answer. The problem is in the component react-native-basic-form
(i.e. ./node_modules/react-native-basic-form/helpers/TextInput.js) 

Line 32, somehow that property is not valid. I don't know if the version of react-native that I use has the bug, or your original code, brought that "buggy" version of the component react-native-basic-form
Anyway, I'm going to document that to the owners of the components.

Sorry to bother you!
Be safe,
I

import React, {useState} from 'react';
import {View, StyleSheet} from 'react-native';

import {Input, Icon} from 'react-native-elements';

const TextInput = (props) => {
    let {label, value, errorMessage, placeholder, secure, onChangeText, testID} = props;

    //Other Props                                                                                                                                    
    let {autoCapitalize, autoCorrect, clearButtonMode, editable, multiline, keyboardType} = props;

    const [visible, setVisibility] = useState(secure);

    const { iconSize, iconColor} = props;

    const toggleVisibility = () => setVisibility(!visible);

    return (
        <View style={styles.container}>
            <Input
                label={label}
                value={value}
                placeholder={placeholder}
 **------        errorMessage={errorMessage}**
                secureTextEntry={visible}
                onChangeText={onChangeText}
                testID={testID}

                autoCapitalize={autoCapitalize}
                autoCorrect={autoCorrect}
                clearButtonMode={clearButtonMode}
                //editable={editable}                                                                                                                
                multiline={multiline}
                keyboardType={keyboardType}

**Comment by MosesEsan** [comment]
@qonteo  Are you still getting the same error after commenting out the editable?

**Comment by qonteo** [comment]
No, the error is gone. The fix is explained above. Thanks 

Now, I'm stuck in the Username screen. There's no "go-back" button, and the registration process doesn't store username.

Anyway, it's something that I need to extend and customize you code.

By the way, how to I access the header controls, such as the goback button  "<-" that shows in the Login  and Register screens, but it doesn't in the Username screen?
What is the respective file to customize it?

**Comment by MosesEsan** [comment]
@qonteo I updated the package, if you follow the tutorial and look at React navigation documentation you should be able to fix any issue you have

**Comment by qonteo** [comment]
![image](https://user-images.githubusercontent.com/64494340/82602662-d1bdf980-9b87-11ea-8848-cdd0a4b67b84.png)


Just to you visualize the screen I have.

Okay, I'm going to download your changes

**Comment by qonteo** [comment]
> @qonteo I updated the package, if you follow the tutorial and look at React navigation documentation you should be able to fix any issue you have

I haven't found your new commit
...
mesan-react-native-cli-authentication-app$ git pull
Already up to date.


What is the branch?

**Comment by qonteo** [comment]
![image](https://user-images.githubusercontent.com/64494340/82605587-8c4ffb00-9b8c-11ea-8710-74b3f8901386.png)

I guess you uploaded the new  code to the expo repository. I'm on react-native-cli repository.
Neither master branch, nor crud-events branch is up to date.

In parallel check your LinkedIn account.

**Comment by MosesEsan** [comment]
@qonteo run npm i --save react-native-basic-form@latest 

Please follow the tutorial and use the packages documentations.
