### ISSUE TITLE
Why PUT instead of POST

### ISSUE THREAD

**Issue by qonteo** [MosesEsan/mesan-react-native-cli-authentication-app#3]
Hello Moses,
Debugging an issue I had in my Webserver, regarding method PUT not allowed, I started to wonder about the reason, which made you use axios.PUT instead of axios.POST. Even because you wrote Content-Type": "multipart/form-data", as the input format.

Is there any particular reason?

https://github.com/MosesEsan/mesan-react-native-cli-authentication-app/blob/master/app/services/auth.js

Why are you using axios.PUT instead of axios.POST?

References: 9 Method Definitions
https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

**Comment by MosesEsan** [comment]
Please follow the tutorial, all questions should be asked on the medium page not on this repo.
